var story ={
  "dialogs": [[0, "Greetings Dr !!user, as one of the greatest minds of this century, next to me of course, I'll put you in charge of my lastest creation: the Civient!!.", "scientist.png", "right"],
  [1, "Civ", "nicubunu_Game_baddie_Basic_guy.png", "left"],
  [2, "These creatures have the ability to duplicate themselves rapidly with controlled mutations directed into an specific area", "scientist.png", "right"],
  [3, "After working hard on a day, they can choose which area to improve depending on what they prefer.", "scientist.png", "right"],
  [4, "Just imagine it, enough about letting nature and randomness control who survives and who doesn't or how we live and are, its time to do it ourselves", "scientist.png","right"],
  [5, "Now, the reason we need you, is to control a planet filled with civients. Your work is to make them the most advanced civilization in the universe, for no evil reasons of course.", "scientist.png", "right"],
  [6, "Your job will be to assign as much daily activities to the civients as you can, so they learn as much as possible.", "scientist.png", "right"],
[7, "I'll let my right hand civient to explain the technicalities", "scientist.png", "right"],
[11, "Hello! I'm the professor's personal civient, I'll guide you on how to control your world or newly created civients.", "nicubunu_Game_baddie_Geisha.png", "left"],
[12, "The civients you will guide still don't know your language but you'll have an automatic translator to be able to understand their feelings, so don’t worry about communication.", "nicubunu_Game_baddie_Geisha.png", "left"],
[13, "I will surround in a yellow frame the things I want to show you, so first here at the top you have the activities you have to distribute.", "nicubunu_Game_baddie_Geisha.png", "left"],
[14, "Below you have the civients that will work for you. These are the ones that will make the activities.", "nicubunu_Game_baddie_Geisha.png", "left"],
[15, "In order to assign the activities you must start with one of the leftmost activities, as the activities must be done in the order they appear if they are of the same color. (inner)", "nicubunu_Game_baddie_Geisha.png", "left"],
[16, "So first we will assign this activity to the civient that is able to do that activity.", "nicubunu_Game_baddie_Geisha.png", "left"],
[17, "These are the activities we can assign next, you should also know that once you assign an activity you cannot go back on your decision.", "nicubunu_Game_baddie_Geisha.png", "left"],
[18, "Now I will assign the second activity of the same type. As you can see, there is a line that indicates which activity should be completed before your current activity.", "nicubunu_Game_baddie_Geisha.png", "left"],
[19, "You'll see that this activity will be placed after the first one has finished, even if the civient was free before.", "nicubunu_Game_baddie_Geisha.png", "left"],
[10, "Now I’m grabbing the first purple activity, if I place it here it will be placed after the lime green activity", "nicubunu_Game_baddie_Geisha.png", "left"],
[21, "But if I place it over the lime green activity it will be placed before, I’ll place it here", "nicubunu_Game_baddie_Geisha.png", "left"],
[22, "As you can see, the purple activity is now the first activity and moved the positions of the lime green activities.", "nicubunu_Game_baddie_Geisha.png", "left"],
[23, "Now I’ll place this activity", "nicubunu_Game_baddie_Geisha.png", "left"],
[24, "I guess another one here", "nicubunu_Game_baddie_Geisha.png", "left"],
[25, "mmm next one here", "nicubunu_Game_baddie_Geisha.png", "left"],
[26, "Now I’ll make a wrong move just to show you what happens, I’ll place this activity before the purple one", "nicubunu_Game_baddie_Geisha.png", "left"],
[27, "Whoops!!, seems as if the activities could not fit on the time limit", "nicubunu_Game_baddie_Geisha.png", "left"],
[28, "This happened because the pink activity pushed the purple and the green one further,", "nicubunu_Game_baddie_Geisha.png", "left"],
[29, "and the green activity of the civient of 4 colors was supposed to be done before the lime green activity of the brick civient", "nicubunu_Game_baddie_Geisha.png", "left"],
[30, "so moving the first lime green activity moved the second one and it passed the time limit", "nicubunu_Game_baddie_Geisha.png", "left"],
[31, "I’ll return in time (something that you are not and won’t be able to do) and place the activity here instead", "nicubunu_Game_baddie_Geisha.png", "left"],
[32, "The next one here...","nicubunu_Game_baddie_Geisha.png", "left"],
[33, "And finally the last one, mmm I guess here", "nicubunu_Game_baddie_Geisha.png", "left"],
[34, "Whoops again!!, I guess I got something wrong", "nicubunu_Game_baddie_Geisha.png", "left"],
[35, "Thankfully our scientists will work the whole day, while the civients follow your orders to get an answer (Top is my answer)", "nicubunu_Game_baddie_Geisha.png", "left"],
[36, "Now I can see how placing the purple activity before the green one affected the results", "nicubunu_Game_baddie_Geisha.png", "left"],
[37, "Something important I forgot to mention, is that the points you’ll get are dependant on the percentage that you completed without the overflow.", "nicubunu_Game_baddie_Geisha.png", "left"],
[38, "The percentage of the last move is the one that counts. Also, if you get a score under 85% you won’t get any points, so try to get as much activities as you can completed", "nicubunu_Game_baddie_Geisha.png", "left"],
[39, "Don't worry if you are not able to do all of these puzzles, some are actually difficult. Now you could ask, why would I want points?", "nicubunu_Game_baddie_Geisha.png", "left"],
[40, "Here is the shop. Here you will be able to improve your civient's world in many different aspects, your civients will evolve and become able to do different things.", "nicubunu_Game_baddie_Geisha.png", "left"],
[41, "Every three sets you buy from a specific skill you'll see something new happening to your world, so I'll recommend you buy things three by three.", "nicubunu_Game_baddie_Geisha.png", "left"],
[41, "Also, the more points you have the more difficult will the problems get", "nicubunu_Game_baddie_Geisha.png", "left"],
[42, "Hi, I come from the future, everything is great thanks for everything", "nicubunu_Game_baddie_Borg.png", "left"],
[43, "I guess I explained well then, that’s all you need to know, so let’s get started !!", "nicubunu_Game_baddie_Geisha.png", "left"]],
"scenes": [["background_lab.jpg", 0, false], ["tutorial_activities.png", 10, true], ["tutorial_machines.png", 11, true], ["tutorial_first_selection.png", 12, true], ["tutorial_1_move.png", 13, true], ["tutorial_1_move2.png", 14, true], ["tutorial_2_move.png", 15, true], ["tutorial_2_move2.png", 16, true],
  ["tutorial_3_move_after.png", 17, true], ["tutorial_3_move_before.png", 18, true], ["tutorial_3_move2.png", 19, true], ["tutorial_4_move.png", 20, true], ["tutorial_5_move.png", 21, true], ["tutorial_6_move.png", 22, true],
  ["tutorial_wrong_move.png", 23, true], ["tutorial_overflow.png", 24, true], ["tutorial_overflow2.png", 25, true], ["tutorial_correct_move.png", 28, true], ["tutorial_correct_2_move.png", 29, true], ["tutorial_last_move.png", 30, true], ["tutorial_last_overflow.png", 31, true],
  ["tutorial_science_answer.png", 32, true], ["tutorial_last_move.png", 34, true], ["background_tutorial_shop.png", 37, true], ["background_tutorial_shop_example.png", 38, true], ["background_lab.jpg", 40, false]],
//strength, intelligence, curiosity, organization, construction
"levels": [0,0,0,0,0]
}
